import React,{useState,useEffect} from 'react';
type Config={title:string;actions:string[];samples:Record<string,Record<string,unknown>>};
function defaultRole(a:string){return ['cancel','ship','refund','relay','replay','drain'].includes(a)?'operator':['callback','propose','approve'].includes(a)?'reviewer':['feedback','publish'].includes(a)?'instructor':'learner'}
export default function Workflow(){
 const [config,setConfig]=useState<Config|null>(null),[action,setAction]=useState(''),[role,setRole]=useState('learner'),[fields,setFields]=useState<Record<string,string>>({}),[output,setOutput]=useState<unknown>(null),[state,setState]=useState<Record<string,any>|null>(null),[status,setStatus]=useState('Loading project…'),[busy,setBusy]=useState(false);
 function choose(a:string,c:Config){setAction(a);setRole(defaultRole(a));setFields(Object.fromEntries(Object.entries(c.samples[a]||{}).map(([k,v])=>[k,Array.isArray(v)?JSON.stringify(v):String(v)])));}
 useEffect(()=>{fetch('/api/config').then(r=>{if(!r.ok)throw Error('Project API unavailable');return r.json()}).then(c=>{setConfig(c);choose(c.actions[0],c);setStatus('Ready')}).catch(e=>setStatus(e.message))},[]);
 async function inspect(){const r=await fetch('/api/state',{headers:{Authorization:'Bearer local-operator'}});const data=await r.json();if(!r.ok)throw Error(data.detail||data.message||'State access failed');setState(data);}
 async function submit(e:React.FormEvent){e.preventDefault();if(!config)return;setBusy(true);try{const sample=config.samples[action]||{};const payload=Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,Array.isArray(sample[k])?JSON.parse(v):typeof sample[k]==='number'?Number(v):typeof sample[k]==='boolean'?v==='true':v]));const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer local-'+role},body:JSON.stringify({action,payload})});const data=await r.json();setOutput(data);setStatus(`HTTP ${r.status} · ${r.ok?'Completed':'Rejected'}`);await inspect()}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}
 return <main><p className="eyebrow">INDEPENDENT REFERENCE APPLICATION</p><h1>{config?.title||'Workflow workbench'}</h1><p className="note">Synthetic data. Run a workflow, repeat a request and inspect its audit history. Local fixture roles are for this demonstration only.</p><div className="grid"><section><h2>Workflow</h2><form onSubmit={submit}><label htmlFor="action">Action</label><select id="action" value={action} onChange={e=>config&&choose(e.target.value,config)}>{config?.actions.map(a=><option key={a}>{a}</option>)}</select><label htmlFor="role">Local role</label><select id="role" value={role} onChange={e=>setRole(e.target.value)}>{['learner','operator','reviewer','instructor','partner','clinic-a','clinic-b'].map(r=><option key={r}>{r}</option>)}</select>{Object.entries(fields).map(([key,value])=><div key={key}><label htmlFor={'field-'+key}>{key}</label>{Array.isArray(config?.samples[action]?.[key])?<textarea id={'field-'+key} value={value} onChange={e=>setFields({...fields,[key]:e.target.value})}/>:<input id={'field-'+key} required value={value} type={typeof config?.samples[action]?.[key]==='number'?'number':'text'} onChange={e=>setFields({...fields,[key]:e.target.value})}/>}</div>)}<button disabled={busy||!config} type="submit">{busy?'Working…':'Run workflow'}</button></form><p role="status" aria-live="polite">{status}</p></section><section><h2>Result and audit</h2><button onClick={()=>inspect().catch(e=>setStatus(e.message))}>Refresh state</button><pre aria-live="polite">{JSON.stringify(output,null,2)||'Choose a workflow to begin.'}</pre><details><summary>Inspect current records and audit events</summary><pre>{JSON.stringify(state,null,2)||'Refresh state to inspect records.'}</pre></details></section></div><p className="note">External cloud services are not connected. Source documentation identifies the local implementation and deployment extensions.</p></main>
}
